"""Reader appendices adapted from the conversational manuscript."""
ANNEX_PROMPTS=[
('A1 • Note vocale → brief','Transcris [note autorisée]. Sépare mots exacts, hypothèses et informations manquantes. Produis un brief : public [public], pays [pays], problème, preuve, format, CTA, validation humaine. Ne transforme pas une hypothèse en fait.'),
('A2 • Choisir une niche','Avec [compétences réelles], [temps] et [ville], compare trois publics et problèmes, note preuves et risques ; propose un test peu coûteux sans prédire de revenu.'),
('A3 • Analyser un marché','Étudie [secteur, ville, période] avec [observations datées]. Sépare données officielles, observations et inconnues. Liste prix, livraison et paiement à confirmer ; ne calcule pas un marché fictif.'),
('A4 • Analyser une audience','Classe [questions anonymisées] en besoins, mots employés, objections et urgences. Indique la taille non représentative de l’échantillon et propose trois nouvelles questions.'),
('A5 • Concurrents sans copier','Pour [liens publics, date], relève uniquement promesses, thèmes et questions laissées ouvertes. N’emprunte aucun script, exemple personnel ou habillage distinctif ; propose mes angles originaux.'),
('A6 • Tendances','Sur [plateforme, pays, période], relève les sujets observés avec liens et dates ; ne présume pas leur popularité sans données. Marque les tendances non confirmées.'),
('A7 • Comparer des plateformes','Pour [public/pays/temps], compare TikTok, YouTube, Instagram et Facebook selon formats, découverte, analyse, offre et contraintes ; cite la documentation officielle et sépare faits d’hypothèses.'),
('A8 • Trente idées','Avec [pilier, public, questions], propose 30 idées originales, une question et une preuve à vérifier pour chacune ; classe risque et CTA. Aucune garantie de viralité.'),
('A9 • Hooks','Pour [sujet, preuve], propose cinq ouvertures honnêtes. Pour chacune, dis quelle information la vidéo doit livrer afin de ne pas tromper.'),
('A10 • Script','Écris pour [public] un script original de [durée] sur [sujet] : hook, problème, démonstration, limite et CTA unique. Faits autorisés : [sources]. Signale les simulations.'),
('A11 • Série','Décline [problème] en cinq épisodes complémentaires, chacun avec question, preuve, format et rappel vers l’épisode suivant ; évite les répétitions.'),
('A12 • Storyboard','Pour [script], établis SEGMENT_001… avec cadrage, texte écran, audio, média, droits, durée estimée et test technique. N’affirme pas avoir créé des fichiers.'),
('A13 • Image','Rédige un prompt d’image originale pour expliquer [concept], palette [couleurs], format [ratio], sans texte, logo ou interface officielle ; indique alt text et vérification des droits.'),
('A14 • Vidéo','Pour [storyboard], prépare un prompt de plan animé avec mouvement, durée, média de départ autorisé et vérification humaine. Ne dis pas qu’une vidéo a été rendue si aucun MP4 n’existe.'),
('A15 • Voix off','Segmente [script] pour lecture naturelle. Propose les pauses et prononciations à vérifier. N’imite pas une personne réelle et demande son autorisation pour sa voix.'),
('A16 • Sous-titres','À partir de [transcription autorisée], propose des sous-titres segmentés. Marque les noms, nombres et négations à relire à l’écoute avant publication.'),
('A17 • Publication','Pour [contenu, plateforme, pays], propose une légende claire, un CTA et une déclaration commerciale ou IA à vérifier selon les règles du service ; pas de hashtags inventés comme tendance.'),
('A18 • Statistiques','Pour [tableau, période, définitions], calcule les ratios aux dénominateurs connus ; distingue vues, demandes et paiements. Donne incertitudes et prochain test.'),
('A19 • Optimisation','Avec [trois à cinq publications comparables], propose une seule hypothèse de changement, sa métrique et les explications alternatives. Aucune causalité inventée.'),
('A20 • Offre','Pour [problème, public, prix fourni], construis livrable, délai, exclusions, coûts, conditions et test pilote. Ne garantis ni croissance ni revenu.'),
('A21 • Vendre un service','Avec [compétence démontrable], prépare une fiche de service, devis-type et étapes de livraison ; indique ce qui n’est pas inclus et les règles locales à vérifier.'),
('A22 • Produit numérique','À partir de [tâche répétée], propose une checklist ou un modèle pilote ; ajoute mode d’emploi, test, droits et mise à jour sans promesse financière.'),
('A23 • Reporting','Pour [données anonymes], définis tableau, périodicité, source, gestion des valeurs manquantes et contrôle humain. Aucune publication ni connexion automatique sans permission.'),
('A24 • Vérifier les droits','Pour [actif et URL], distingue auteur, licence applicable, attribution, consentement des personnes, marques et usage commercial ; indique non confirmé quand nécessaire.'),
('A25 • Transcription tierce','Résume [transcription autorisée] en idées générales ; ne reproduis ni phrases reconnaissables, ni cas personnel comme le mien ; attribue les idées et propose une structure originale.'),
('A26 • Vérifier un outil','Pour [nom], [pays], ouvre documentation officielle ; liste lien, fonction, coût seulement confirmé, formats, licence, API documentée et limitations. Aucun accès présumé.'),
('A27 • Contrôle qualité','Audite [fichier réel] : intégrité, texte, sources, droit des médias, titres, liens, pagination et lisibilité. Marque non vérifié tout contrôle non exécuté.')]
GLOSSARY={'Audience':'personnes qui voient ou suivent un contenu, selon la mesure de chaque service.','Brief':'fiche définissant objectif, public, preuve, format et contrôle.','CTA':'appel à l’action, prochaine étape proposée au public.','Conversion':'action spécifiée, mesurée avec une période et un dénominateur.','Hook':'ouverture qui annonce l’intérêt réel de la vidéo.','Niche':'combinaison d’un public, d’un problème et d’un angle.','Rétention':'mesure de poursuite du visionnage selon la définition du service.','Workflow':'suite documentée d’entrées, actions, contrôles et sorties.','YPP':'YouTube Partner Program, sous conditions territoriales et de compte.'}
CALENDAR=[(1,7,'Fondations : profil, compétence, objectif, niche provisoire, public, canal principal.'),(8,14,'Recherche : audience, concurrents, piliers, identité, idées et scripts.'),(15,21,'Production : téléphone, son, montage, sous-titres, publication et suivi.'),(22,30,'Bilan : séries, hooks, retours, ressource ou offre pilote.'),(31,45,'Consolidation : cadence réaliste, adaptation originale, prospects consentis, CTA et reporting.'),(46,60,'Documentation : fichiers, tableau de bord, automatisation réversible et prochain plan.')]
SOURCES=[
('S01','TikTok Support — Creator Rewards Program','https://support.tiktok.com/en/business-and-creator/creator-rewards-program/creator-rewards-program','Général ; région admissible à vérifier'),
('S02','TikTok Support — How rewards work','https://support.tiktok.com/en/business-and-creator/creator-rewards-program/how-rewards-work','Général ; méthodes de paiement nommées pour certains pays'),
('S03','TikTok — Conditions du Programme de Récompenses pour les créateurs','https://www.tiktok.com/legal/page/global/tiktok-creator-rewards-program-eea/fr','France/EEE ; version avril 2025'),
('S04','TikTok Support — Promoting a brand, product, or service','https://support.tiktok.com/en/business-and-creator/creator-and-business-accounts/promoting-a-brand-product-or-service','Règle de déclaration commerciale'),
('S05','TikTok Support — Account types on TikTok','https://support.tiktok.com/en/using-tiktok/growing-your-audience/switching-to-a-creator-or-business-account','Type de compte et outils ; région à vérifier'),
('S06','YouTube Help — Partner Program overview & eligibility','https://support.google.com/youtube/answer/72851?hl=en','Général ; pays admissible requis'),
('S07','YouTube Help — Disponibilité du Programme Partenaire','https://support.google.com/youtube/answer/7101720?hl=fr','Liste territoriale YPP standard'),
('S08','YouTube Help — Changes to YPP','https://support.google.com/youtube/answer/12843009?hl=en','Annonce des seuils à venir au 1er février 2027'),
('S09','Meta — Partner Monetization Policies','https://www.facebook.com/business/help/169845596919485','Facebook ; disponibilité par produit et pays'),
('S10','PayPal — Tarification pour les particuliers, Bénin','https://www.paypal.com/bj/digital-wallet/paypal-consumer-fees','Bénin ; tarif ≠ disponibilité de réception/retrait'),
('S11','Gumroad — Getting paid','https://gumroad.com/help/article/13-getting-paid','Table des pays et devises de virement'),
('S12','Chariow — FAQ et frais','https://chariow.com/fr/faq','Information divergente avec https://help.chariow.com/en/articles/64-what-are-the-fees-on-chariow'),
('S13','ITC — SMEs drive e-payment growth in francophone Africa','https://www.intracen.org/news-and-events/news/smes-drive-e-payment-growth-in-francophone-africa-but-challenges-persist','Enquête 2025 : échantillon de 5 453 entreprises/18 pays')]
