"""Visual concepts derived only from the 39 headings and adapted source chapters.
Each visual is a new editable Word table, not a statistic, UI, or platform logo.
"""
CONCEPTS=[
('Chaîne de responsabilité','Humain → préparation IA → validation humaine',['Question réelle','Proposition IA','Vérification','Publication choisie']),
('Actif et canal','Compte et audience ne sont pas propriété commerciale',['Compte tiers','Public touché','Relation consentie','Offre livrable']),
('Matrice de délégation','Trois niveaux de risque, pas une décision automatique',['Assister : idées','Vérifier : faits','Valider : promesse','Autoriser : action']),
('Inventaire personnel','Les ressources limitent le projet réaliste',['Savoir-faire','Preuve disponible','Temps et moyens','Sujet testable']),
('Entonnoir de niche','De la compétence à la promesse prudente',['Compétence','Problème réel','Public précis','Niche provisoire']),
('Fiche d’observation','Une observation n’est pas une preuve de marché général',['Parole recueillie','Source et date','Interprétation','Hypothèse à tester']),
('Grille concurrentielle','Observer une question sans copier la réponse',['Compte public','Question abordée','Limite constatée','Angle original']),
('Choix de canal','Comparer l’adéquation sans présumer la disponibilité',['Public visé','Format tenable','Canal principal','Test daté']),
('Positionnement','Six composantes d’une identité crédible',['Public','Problème','Approche','Preuve autorisée']),
('Piliers éditoriaux','Chaque pilier répond à une fonction',['Découverte','Confiance','Communauté','Conversion']),
('Banque d’idées','Une idée doit passer par la vérification',['Question reçue','Idée classée','Preuve requise','Brief prêt']),
('Structure du script','Un hook doit être honoré par la vidéo',['Accroche honnête','Contexte','Démonstration','Action unique']),
('Contrôle du tournage','Un téléphone suffit pour un test techniquement propre',['Lumière','Stabilité','Son','Lecture test']),
('Boucle de communauté','Répondre nourrit les prochaines idées',['Publication','Question reçue','Réponse utile','Sujet suivant']),
('Transformation en brief','Du sujet au contenu vérifié',['Question','Source','Brief','Script relu']),
('Registre des médias','Chaque couche demande ses droits propres',['Image','Voix et musique','Sous-titres','Droits contrôlés']),
('Cinq étapes vidéo','Production par segment avec prototype',['Segment et voix','Storyboard','Son','Animation','Export testé']),
('Test d’outil','Choisir l’outil selon l’export réel',['Tâche','Fonction vérifiée','Essai court','Fichier ouvert']),
('Traçabilité des fichiers','Un nom stable relie les versions',['SEGMENT_001','audio_SEGMENT_001','visual_SEGMENT_001','video_SEGMENT_001']),
('Mesures distinctes','Ne pas confondre visibilité et revenu',['Portée','Consommation','Demandes','Paiements reçus']),
('Boucle d’apprentissage','Tester une hypothèse sur des contenus comparables',['Publier','Mesurer','Interpréter','Modifier']),
('Trois niveaux','Le contrôle croît avec les conséquences',['Assistance','Workflow','Automatisation','Validation adaptée']),
('Agent et preuve','Une sortie d’agent doit être auditable',['Données autorisées','Agent et outil','Rapport sourcé','Relecture humaine']),
('Matrice de risque','La validation dépend du caractère réversible',['Donnée privée','Fait sensible','Publication','Paiement']),
('Parcours économique','La vente n’est pas automatique',['Besoin','Confiance','Offre claire','Achat éventuel']),
('Éligibilité native','Les programmes sont des produits distincts',['Produit exact','Pays réel','Conditions actuelles','Compte vérifié']),
('Fiche de service','Les engagements doivent être bornés',['Problème','Livrable','Délai','Limites']),
('Prototype numérique','Tester avant de généraliser',['Tâche répétée','Prototype','Test d’usage','Livraison']),
('Relation commerciale','Divulguer les intérêts du créateur',['Partenaire','Conditions écrites','Divulgation','Public informé']),
('Parcours de contact','L’intérêt exige consentement et suivi',['CTA clair','Consentement','Proposition','Désinscription']),
('Sécurité du compte','Le contrôle des accès précède la publication',['Identité réelle','Accès sécurisé','Profil exact','Sessions suivies']),
('Décision par pays','Ne jamais déduire une éligibilité d’un autre pays',['Pays réel','Règles officielles','Compte admissible ?','Paiement confirmé ?']),
('États du paiement','Estimation ne signifie pas argent reçu',['Estimé','Validé','Payable','Encaissé']),
('Diagnostic de paiement','Vérifier séparément chaque maillon',['Programme','Prestataire','Retrait local','Fiscalité']),
('Fiche locale','Un pays ne représente pas toute une région',['Pays et ville','Langue','Offre livrable','Paiement réel']),
('Premier mois','Construire des preuves plutôt que promettre un résultat',['Jours 1–7','Jours 8–14','Jours 15–21','Jours 22–30']),
('Consolidation','Les jours 31 à 60 suivent le premier mois',['Jours 31–45','Offre testée','Jours 46–60','Workflow documenté']),
('Parcours par profil','Adapter les preuves au rôle réel',['Débutant','Commerçant','Formateur','Freelance']),
('Système reproductible','Tracer chaque boucle de création',['Recherche','Production','Publication','Mesure','Documentation'])]
assert len(CONCEPTS)==39
PART_THEMES=['L’humain garde le cap','Trouver un besoin réel','Éclaircir son message','Produire avec discernement','Apprendre des mesures','Offrir une valeur livrable','Vérifier le pays et les règles','Construire, puis consolider']
